version: '3'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - 27017:27017
      
  microservice1:
    build: .
    ports:
      - 3000:3000
   
    networks:
      - mynetwork
    depends_on:
      - mongodb
networks:
  mynetwork:
    driver: bridge
